---
- set_fact:
    gitlab_host_dirs: |
        {% set directories = [] %}
        {% for gitlab_volume in gitlab_volumes %}
        {% set d = gitlab_volume.split(':')[0] %}
        {% set _ = directories.append(d) %}
        {% endfor %}
        {{ directories | to_json }}
- file:
    path: "{{item}}"
    mode: "0711"
    state: directory
  with_items: "{{gitlab_host_dirs}}"
- template:
    src: gitlab.rb
    dest: "{{gitlab_volumes_hostdir}}/etc/gitlab.rb"
    mode: "0644"
    trim_blocks: false

- template:
    src: "{{item}}"
    dest: "{{gitlab_volumes_hostdir}}/backupswrapper/{{item}}"
    mode: "0750"
    trim_blocks: false
  with_items: [cronw.sh, cron.sh]
- template:
    src: "{{item}}"
    dest: "{{gitlab_volumes_hostdir}}/backupswrapper/{{item}}"
    mode: "0640"
    trim_blocks: false
  with_items: [gitlab.crontab]

- include_tasks: sshkey.yml
  loop_control: {loop_var: sshkey}
  with_items: "{{gitlab_ssh_keys}}"
- template:
    src: docker-compose.yml
    dest: "{{gitlab_volumes_hostdir}}/docker-compose.yml"
    mode: "0644"
    trim_blocks: false
