- include_role:
    name: corpusops.roles/docker_compose_service
  vars:
    _docker_compose_service:
      project: "{{gitlab_compose_project}}"
      state: "{{gitlab_started_state}}"
      working_directory: "{{gitlab_volumes_hostdir}}"
      stdout: "{{gitlab_stdout}}"
      stderr: "{{gitlab_stderr}}"
- shell: |-
    set -ex
    cd "{{gitlab_volumes_hostdir}}"
    docker-compose -p {{gitlab_compose_project}} up -d
