---
# {{ansible_managed}}
version: '3.8'
networks:
  {{gitlab_net_name}}:
    driver: bridge
    ipam: {driver: default, config: [{subnet: "{{gitlab_network}}.0/24"}]}
x-images:
  vol: &volumes
{%- macro volumes() %}
    volumes:
    - "./rclone.conf:/root/.config/rclone/rclone.conf:ro"
    - "/srv/docker/gitlab/scripts:/scripts"
    {% for i in gitlab_volumes %}
    - "{{ i }}"
    {% endfor %}
    {% for sshkey in gitlab_ssh_keys %}
    - "{{gitlab_volumes_hostdir}}/etc/ssh_host_{{sshkey.type}}_key:/etc/ssh/ssh_host_{{sshkey.type}}_key:ro"
    - "{{gitlab_volumes_hostdir}}/etc/ssh_host_{{sshkey.type}}_key.pub:/etc/ssh/ssh_host_{{sshkey.type}}_key.pub:ro"
    {% endfor %}
{%- endmacro%}
{{-volumes()}}
services:
  web:
    <<: [ *volumes ]
    privileged: {{gitlab_privileged}}
    networks:
      {{gitlab_net_name}}: {ipv4_address: "{{gitlab_int_ip}}"}
    image: "{{gitlab_image}}"
    # image: "gitlab/gitlab-ce:X.X.X-ce.X"
    restart: always
    hostname: "{{gitlab_domain}}"
    ports: {{gitlab_simple_ports}}
  backup:
    volumes:
      - "./backupswrapper:/backupswrapper:ro"
      - "./backupswrapper/gitlab.crontab:/etc/cron.d/gitlab:ro"
      - /var/run/docker.sock:/var/run/docker.sock
      # - /usr/bin/docker:/usr/bin/docker:ro
      # - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7:ro
    entrypoint: [/bin/supervisord.sh]
    image: corpusops/ubuntu:20.04
    networks:
      {{gitlab_net_name}}: {ipv4_address: "{{gitlab_network}}.3"}
    environment:
    - SUPERVISORD_CONFIGS=/etc/supervisor.d/cron /etc/supervisor.d/rsyslog
    restart: always
  scripts:
    {{volumes()}}
    build:
      context: .
      dockerfile: Dockerfile.scripts
    entrypoint: "sh -c 'while true;do sleep 1;done'"
    restart: always
    networks:
      {{gitlab_net_name}}: {ipv4_address: "{{gitlab_network}}.5"}
# vim: set ft=sls :
